/**
 * Codex — Banner (Minecraft-style heraldry) model + compose.
 *
 * The structured source of truth behind the in-app banner designer. A banner is a **base dye**
 * plus an ordered **painter's stack** of pattern layers, each a `{ pattern, color }` pair:
 *
 *   value = { base: <dyeId>, layers: [ { pattern: <patternId>, color: <dyeId> }, … ≤ MAX_LAYERS ] }
 *
 * `bannerToSvg` is the ONE place that turns that value into markup — mirroring
 * `glyphModel.layersToSvg` — so consumers only ever read the derived string. The rendering is
 * recomputed from the (tiny) value on every read; there is no derived blob to store or keep in sync.
 *
 * Patterns are **pixel-exact**: each is a 20×40 per-pixel ALPHA mask extracted from Minecraft's own
 * banner textures (`bannerPatterns.data.js`, generated by `scripts/extract-banner-patterns.ps1`).
 * Alpha (0–255) carries the shape AND Minecraft's edge anti-aliasing, so nothing here is hand-drawn
 * or synthetically feathered — the pattern id is the game's own (`creeper`, `stripe_top`, …).
 * `bannerToSvg` paints each layer's alpha in its dye, coalescing equal-coverage cells into
 * **run-length merged `<rect>`s** (rows then columns) so output stays crisp vector at any scale.
 *
 * Pure and Node-testable: no DOM, no SDK. The designer component (browser-only) drives it.
 */

import { BANNER_PATTERN_ALPHA } from './bannerPatterns.data.js';

/** The banner face in mask/user space — Minecraft's 20 wide × 40 tall texture. */
export const BANNER_W = 20;
export const BANNER_H = 40;
export const VIEWBOX = `0 0 ${BANNER_W} ${BANNER_H}`;

/** The loom cap: at most 6 pattern layers over the base (mirrors the game). */
export const MAX_LAYERS = 6;

/**
 * The 16 canonical Minecraft dye colors. `id` is the stored key (never a hex — hexes can be
 * re-tuned without a data migration); `hex` is what `bannerToSvg` paints. Order matches the
 * in-game dye order, which the swatch grid renders directly.
 */
export const DYE_COLORS = [
  { id: 'white', name: 'White', hex: '#F9FFFE' },
  { id: 'light_gray', name: 'Light Gray', hex: '#9D9D97' },
  { id: 'gray', name: 'Gray', hex: '#474F52' },
  { id: 'black', name: 'Black', hex: '#1D1D21' },
  { id: 'brown', name: 'Brown', hex: '#835432' },
  { id: 'red', name: 'Red', hex: '#B02E26' },
  { id: 'orange', name: 'Orange', hex: '#F9801D' },
  { id: 'yellow', name: 'Yellow', hex: '#FED83D' },
  { id: 'lime', name: 'Lime', hex: '#80C71F' },
  { id: 'green', name: 'Green', hex: '#5E7C16' },
  { id: 'cyan', name: 'Cyan', hex: '#169C9C' },
  { id: 'light_blue', name: 'Light Blue', hex: '#3AB3DA' },
  { id: 'blue', name: 'Blue', hex: '#3C44AA' },
  { id: 'purple', name: 'Purple', hex: '#8932B8' },
  { id: 'magenta', name: 'Magenta', hex: '#C74EBD' },
  { id: 'pink', name: 'Pink', hex: '#F38BAA' },
];

const DYE_BY_ID = new Map(DYE_COLORS.map((d) => [d.id, d]));

/** The default dye when a base/layer color is missing or unknown. */
const DEFAULT_DYE = 'white';

// ── The pattern vocabulary ───────────────────────────────────────────────────
// `[id, human name]` in palette order. The id is Minecraft's own pattern key (the alpha mask is
// looked up in BANNER_PATTERN_ALPHA); the name pairs a plain label with the heraldic/loom term so
// it reads for a newcomer yet is recognizable on a loom or needcoolershoes.
const PATTERN_ORDER = [
  ['stripe_top', 'Top Stripe (Chief)'],
  ['stripe_bottom', 'Bottom Stripe (Base)'],
  ['stripe_left', 'Left Stripe (Pale Dexter)'],
  ['stripe_right', 'Right Stripe (Pale Sinister)'],
  ['stripe_center', 'Center Stripe (Pale)'],
  ['stripe_middle', 'Middle Stripe (Fess)'],
  ['small_stripes', 'Small Stripes (Paly)'],
  ['stripe_downright', 'Down-Right Stripe (Bend)'],
  ['stripe_downleft', 'Down-Left Stripe (Bend Sinister)'],
  ['half_horizontal', 'Top Half (Per Fess)'],
  ['half_horizontal_bottom', 'Bottom Half'],
  ['half_vertical', 'Left Half (Per Pale)'],
  ['half_vertical_right', 'Right Half'],
  ['square_top_left', 'Top-Left Square'],
  ['square_top_right', 'Top-Right Square'],
  ['square_bottom_left', 'Bottom-Left Square'],
  ['square_bottom_right', 'Bottom-Right Square'],
  // Names describe the filled (drawn) triangle, verified against the mask data by which corner is
  // empty. Minecraft's ids are counterintuitive: left/right match the visual, but the `up_` prefix
  // labels the LOWER triangle — so `diagonal_up_left` fills the lower-left. Don't "correct" these.
  ['diagonal_left', 'Upper-Left Diagonal'],
  ['diagonal_right', 'Upper-Right Diagonal'],
  ['diagonal_up_left', 'Lower-Left Diagonal'],
  ['diagonal_up_right', 'Lower-Right Diagonal'],
  ['straight_cross', 'Square Cross'],
  ['cross', 'Diagonal Cross (Saltire)'],
  ['triangle_bottom', 'Bottom Triangle (Chevron)'],
  ['triangle_top', 'Top Triangle'],
  ['triangles_bottom', 'Bottom Sawtooth (Base Indented)'],
  ['triangles_top', 'Top Sawtooth (Chief Indented)'],
  ['circle', 'Circle (Roundel)'],
  ['rhombus', 'Rhombus (Lozenge)'],
  ['border', 'Border (Bordure)'],
  ['curly_border', 'Curly Border (Bordure Indented)'],
  ['bricks', 'Bricks (Field Masoned)'],
  ['gradient', 'Gradient'],
  ['gradient_up', 'Gradient Upside-Down (Base Gradient)'],
  ['creeper', 'Creeper Charge'],
  ['skull', 'Skull Charge'],
  ['flower', 'Flower Charge'],
  ['mojang', 'Thing (Mojang)'],
  ['globe', 'Globe'],
  ['piglin', 'Snout (Piglin)'],
  ['guster', 'Guster'],
  ['flow', 'Flow'],
];

/** base64 → bytes, isomorphic across browser (`atob`) and Node (`Buffer`). */
const b64ToBytes = (s) => {
  const bin = typeof atob === 'function' ? atob(s) : Buffer.from(s, 'base64').toString('binary');
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
};

/**
 * The one pattern registry: `{ id: { name, alpha } }`, built from PATTERN_ORDER + the extracted
 * masks. `alpha` is a Uint8Array of 800 (20×40, row-major) coverage bytes. A PATTERN_ORDER id with
 * no extracted mask is skipped with a warning rather than shipping a broken entry.
 */
export const PATTERNS = {};
for (const [id, name] of PATTERN_ORDER) {
  const b64 = BANNER_PATTERN_ALPHA[id];
  if (!b64) {
    if (typeof console !== 'undefined') console.warn(`bannerModel: no mask for pattern "${id}"`);
    continue;
  }
  PATTERNS[id] = { name, alpha: b64ToBytes(b64) };
}

/** The pattern vocabulary as `[{ id, name }]` in palette order — what the designer's picker lists. */
export function patternList() {
  return Object.entries(PATTERNS).map(([id, p]) => ({ id, name: p.name }));
}

// ── Value shape ──────────────────────────────────────────────────────────────

/** A fresh, empty banner: a white base with no layers. */
export function emptyBanner() {
  return { base: DEFAULT_DYE, layers: [] };
}

/**
 * Coerce any stored/legacy value into a well-formed banner. Tolerant by design: an unknown base
 * dye falls back to white, non-array layers become `[]`, each layer keeps its (string) pattern id
 * even if unknown — a pattern from a newer game version must survive a load/save round-trip rather
 * than be silently dropped — with an unknown layer color falling back to white. Caps at MAX_LAYERS.
 */
export function normalizeBanner(value) {
  if (!value || typeof value !== 'object') return emptyBanner();
  const base = DYE_BY_ID.has(value.base) ? value.base : DEFAULT_DYE;
  const rawLayers = Array.isArray(value.layers) ? value.layers : [];
  const layers = rawLayers
    .filter((l) => l && typeof l === 'object' && typeof l.pattern === 'string' && l.pattern)
    .slice(0, MAX_LAYERS)
    .map((l) => ({ pattern: l.pattern, color: DYE_BY_ID.has(l.color) ? l.color : DEFAULT_DYE }));
  return { base, layers };
}

/** True when a banner has no layers — nothing to render as heraldry. */
export function isEmptyBanner(value) {
  return normalizeBanner(value).layers.length === 0;
}

// ── Compose ──────────────────────────────────────────────────────────────────

const hexOf = (dyeId) => (DYE_BY_ID.get(dyeId) || DYE_BY_ID.get(DEFAULT_DYE)).hex;
const fmtOpacity = (c) => String(+c.toFixed(3)).replace(/\.?0+$/, (m) => (m.includes('.') ? '' : m));
const rowsEqual = (a, b) => a.every((v, i) => v === b[i]);

/** An alpha mask → a coverage grid (0–1 per cell), row-major 40×20. */
function coverageGrid(alpha) {
  const grid = [];
  for (let y = 0; y < BANNER_H; y++) {
    const row = new Array(BANNER_W);
    for (let x = 0; x < BANNER_W; x++) row[x] = alpha[y * BANNER_W + x] / 255;
    grid.push(row);
  }
  return grid;
}

/**
 * A coverage grid → merged `<rect>`s. Two-pass coalescing: consecutive identical rows collapse into
 * one band of height `h`, then equal-coverage cells within the band's row merge horizontally. A
 * solid field becomes a single rect — and, crucially, no per-row seams for the browser to
 * anti-alias into hairlines. Partial-coverage cells (edge anti-aliasing, gradients) emit
 * `fill-opacity`.
 */
function gridRects(grid, hex) {
  let out = '';
  let y = 0;
  while (y < grid.length) {
    let h = 1;
    while (y + h < grid.length && rowsEqual(grid[y], grid[y + h])) h++;
    const row = grid[y];
    let x = 0;
    while (x < BANNER_W) {
      const c = row[x];
      if (c <= 0) { x++; continue; }
      let run = 1;
      while (x + run < BANNER_W && row[x + run] === c) run++;
      const op = c < 1 ? ` fill-opacity="${fmtOpacity(c)}"` : '';
      out += `<rect x="${x}" y="${y}" width="${run}" height="${h}" fill="${hex}"${op}/>`;
      x += run;
    }
    y += h;
  }
  return out;
}

/**
 * Compose a banner into its `<svg>` markup: a full-bleed base rect, then each layer's alpha mask
 * painted in its dye, index 0 first (just above the base), last on top. Layers whose pattern id
 * isn't known are skipped (tolerant, like glyph skipping an unknown shape) rather than throwing.
 */
export function bannerToSvg(value, { className = 'banner-svg' } = {}) {
  const banner = normalizeBanner(value);
  let body = `<rect x="0" y="0" width="${BANNER_W}" height="${BANNER_H}" fill="${hexOf(banner.base)}"/>`;
  for (const layer of banner.layers) {
    const pattern = PATTERNS[layer.pattern];
    if (!pattern) continue;
    body += gridRects(coverageGrid(pattern.alpha), hexOf(layer.color));
  }
  return `<svg viewBox="${VIEWBOX}" class="${className}" preserveAspectRatio="xMidYMid meet" aria-hidden="true" shape-rendering="crispEdges">${body}</svg>`;
}

/**
 * A banner's build recipe — the read-view "how to make this in a loom" projection. Layers are in
 * storage order, which is the exact loom application order (bottom-up). An unknown pattern id is
 * surfaced as its raw id so a pattern from a newer game version still reads as *something*.
 */
export function bannerToRecipe(value) {
  const banner = normalizeBanner(value);
  const dye = (id) => DYE_BY_ID.get(id) || { id, name: id, hex: hexOf(id) };
  const base = dye(banner.base);
  return {
    base: { id: base.id, name: base.name, hex: base.hex },
    layers: banner.layers.map((l) => {
      const c = dye(l.color);
      return {
        pattern: l.pattern,
        patternName: PATTERNS[l.pattern]?.name || l.pattern,
        color: c.id,
        colorName: c.name,
        colorHex: c.hex,
      };
    }),
  };
}

// ── Validation ───────────────────────────────────────────────────────────────

/**
 * Validate a banner for save. Returns human-readable problems ([] when valid): a known base dye,
 * an array of at most MAX_LAYERS layers, each layer a known pattern in a known dye.
 */
export function validateBanner(value) {
  const problems = [];
  if (!value || typeof value !== 'object') return ['Banner is missing.'];
  if (!DYE_BY_ID.has(value.base)) problems.push('Base color is not a known dye.');
  const layers = value.layers;
  if (!Array.isArray(layers)) return problems.concat('Layers must be a list.');
  if (layers.length > MAX_LAYERS) problems.push(`A banner holds at most ${MAX_LAYERS} layers.`);
  layers.forEach((l, i) => {
    const where = `Layer ${i + 1}`;
    if (!l || typeof l !== 'object') { problems.push(`${where}: not a layer.`); return; }
    if (!PATTERNS[l.pattern]) problems.push(`${where}: unknown pattern.`);
    if (!DYE_BY_ID.has(l.color)) problems.push(`${where}: color is not a known dye.`);
  });
  return problems;
}
